import 'package:flutter/material.dart';
import 'cb_models.dart';

/// Catalogue de cartes du TCG GameTun (d'après la planche de référence).
class CbData {
  CbData._();

  static const List<CbCard> cards = [
    // ---- CRÉATURES -------------------------------------------------------
    CbCard(
      id: 'recrue_braise',
      name: 'Recrue de Braise',
      element: CbElement.braise,
      type: CbType.creature,
      rarity: CbRarity.common,
      cost: 2, attack: 2, health: 2,
      text: 'Ruée.',
      keywords: {Kw.rush},
      icon: Icons.local_fire_department,
    ),
    CbCard(
      id: 'guerriere_flots',
      name: 'Guerrière des Flots',
      element: CbElement.flots,
      type: CbType.creature,
      rarity: CbRarity.common,
      cost: 3, attack: 3, health: 3,
      text: "Quand elle attaque, soigne 1 PV à ton héros.",
      keywords: {Kw.healHeroOnAttack},
      icon: Icons.water_drop,
    ),
    CbCard(
      id: 'druide_verdant',
      name: 'Druide Verdant',
      element: CbElement.verdant,
      type: CbType.creature,
      rarity: CbRarity.uncommon,
      cost: 3, attack: 2, health: 4,
      text: 'Fin de tour : +1 PV à une unité alliée.',
      keywords: {Kw.healAlliesEot},
      icon: Icons.eco,
    ),
    CbCard(
      id: 'eclaireur_orage',
      name: 'Éclaireur Orage',
      element: CbElement.orage,
      type: CbType.creature,
      rarity: CbRarity.rare,
      cost: 4, attack: 3, health: 4,
      text: 'Ruée. Invoque un Éclat Orage 1/1 à l\'attaque.',
      keywords: {Kw.rush, Kw.summonOnAttack},
      icon: Icons.bolt,
    ),
    CbCard(
      id: 'abyssal_corrompu',
      name: 'Abyssal Corrompu',
      element: CbElement.vide,
      type: CbType.creature,
      rarity: CbRarity.epic,
      cost: 5, attack: 4, health: 4,
      text: 'Vol de vie : tue une unité → gagne +1/+1.',
      keywords: {Kw.growOnKill},
      icon: Icons.dark_mode,
    ),
    CbCard(
      id: 'paladin_lumineux',
      name: 'Paladin Lumineux',
      element: CbElement.lumiere,
      type: CbType.creature,
      rarity: CbRarity.legendary,
      cost: 6, attack: 5, health: 6,
      text: 'Bouclier (2). Survit à des dégâts → pioche 1 carte.',
      keywords: {Kw.shield, Kw.drawOnSurvive},
      shieldValue: 2,
      icon: Icons.wb_sunny,
    ),
    // Jetons
    CbCard(
      id: 'marqueur',
      name: 'Marqueur',
      element: CbElement.flots,
      type: CbType.creature,
      rarity: CbRarity.common,
      cost: 0, attack: 1, health: 1,
      text: 'Provocation.',
      keywords: {Kw.taunt},
      icon: Icons.flag,
    ),
    CbCard(
      id: 'eclat_orage',
      name: 'Éclat Orage',
      element: CbElement.orage,
      type: CbType.creature,
      rarity: CbRarity.common,
      cost: 0, attack: 1, health: 1,
      text: 'Jeton.',
      icon: Icons.flash_on,
    ),
    CbCard(
      id: 'racine',
      name: 'Racine',
      element: CbElement.verdant,
      type: CbType.creature,
      rarity: CbRarity.common,
      cost: 0, attack: 1, health: 1,
      text: 'Jeton.',
      icon: Icons.grass,
    ),

    // ---- SORTS -----------------------------------------------------------
    CbCard(
      id: 'boule_de_feu',
      name: 'Boule de Feu',
      element: CbElement.braise,
      type: CbType.spell,
      rarity: CbRarity.common,
      cost: 2,
      text: 'Inflige 3 dégâts à une unité.',
      spellFx: SpellFx.damageOne, spellValue: 3,
      icon: Icons.whatshot,
    ),
    CbCard(
      id: 'vague_deferlante',
      name: 'Vague Déferlante',
      element: CbElement.flots,
      type: CbType.spell,
      rarity: CbRarity.rare,
      cost: 3,
      text: 'Inflige 2 dégâts à toutes les unités ennemies.',
      spellFx: SpellFx.damageAllEnemies, spellValue: 2,
      icon: Icons.waves,
    ),
    CbCard(
      id: 'racines_etouffantes',
      name: 'Racines Étouffantes',
      element: CbElement.verdant,
      type: CbType.spell,
      rarity: CbRarity.uncommon,
      cost: 4,
      text: 'Immobilise une unité ennemie pendant 2 tours.',
      spellFx: SpellFx.freezeOne, spellValue: 2,
      icon: Icons.park,
    ),
    CbCard(
      id: 'eclair_chaine',
      name: 'Éclair Chaîné',
      element: CbElement.orage,
      type: CbType.spell,
      rarity: CbRarity.uncommon,
      cost: 2,
      text: 'Inflige 2 dégâts à une unité, 1 aux adjacentes.',
      spellFx: SpellFx.chain, spellValue: 2,
      icon: Icons.electric_bolt,
    ),

    // ---- STRUCTURES ------------------------------------------------------
    CbCard(
      id: 'tour_de_garde',
      name: 'Tour de Garde',
      element: CbElement.braise,
      type: CbType.structure,
      rarity: CbRarity.common,
      cost: 3, attack: 0, health: 5,
      text: 'Début de ton tour : +1 Bouclier au héros.',
      keywords: {Kw.heroShieldEot},
      icon: Icons.castle,
    ),
    CbCard(
      id: 'sanctuaire_aquatique',
      name: 'Sanctuaire Aquatique',
      element: CbElement.flots,
      type: CbType.structure,
      rarity: CbRarity.uncommon,
      cost: 4, attack: 0, health: 6,
      text: 'Fin de tour : soigne 1 PV à tes unités.',
      keywords: {Kw.healAlliesEot},
      icon: Icons.temple_buddhist,
    ),
    CbCard(
      id: 'pylone_orageux',
      name: 'Pylône Orageux',
      element: CbElement.orage,
      type: CbType.structure,
      rarity: CbRarity.rare,
      cost: 5, attack: 0, health: 5,
      text: 'Fin de tour : 1 dégât à une unité ennemie.',
      keywords: {Kw.pingEot},
      icon: Icons.cell_tower,
    ),
    CbCard(
      id: 'bastion_lumineux',
      name: 'Bastion Lumineux',
      element: CbElement.lumiere,
      type: CbType.structure,
      rarity: CbRarity.uncommon,
      cost: 4, attack: 0, health: 6,
      text: 'Solide mur défensif.',
      icon: Icons.security,
    ),

    // ---- ARTEFACTS (auras persistantes) ----------------------------------
    CbCard(
      id: 'amulette_braise',
      name: 'Amulette de Braise',
      element: CbElement.braise,
      type: CbType.artifact,
      rarity: CbRarity.uncommon,
      cost: 2,
      text: 'Tes unités gagnent +1 ATQ.',
      icon: Icons.shield_moon,
    ),
    CbCard(
      id: 'coeur_tonnerre',
      name: 'Cœur du Tonnerre',
      element: CbElement.orage,
      type: CbType.artifact,
      rarity: CbRarity.rare,
      cost: 4,
      text: 'Tes unités avec Ruée gagnent +1/+1.',
      icon: Icons.flare,
    ),
  ];

  static final Map<String, CbCard> byId = {for (final c in cards) c.id: c};

  static CbCard card(String id) => byId[id]!;

  // ---- HÉROS -------------------------------------------------------------
  static const List<CbHero> heroes = [
    CbHero(
      id: 'kaelyn',
      name: 'Kaelyn',
      faction: 'Légion de Braise',
      element: CbElement.braise,
      passiveText: 'Tes créatures Braise gagnent +1 ATQ.',
      activeText: 'Inflige 3 dégâts à une unité + Brûlure (2).',
      activeCost: 2,
      icon: Icons.local_fire_department,
      deck: [
        'recrue_braise', 'recrue_braise', 'recrue_braise',
        'boule_de_feu', 'boule_de_feu',
        'guerriere_flots', 'druide_verdant',
        'eclaireur_orage', 'abyssal_corrompu',
        'paladin_lumineux', 'tour_de_garde',
        'amulette_braise', 'amulette_braise',
        'eclair_chaine', 'vague_deferlante', 'bastion_lumineux',
      ],
    ),
    CbHero(
      id: 'nerek',
      name: 'Nerek',
      faction: 'Nés des Flots',
      element: CbElement.flots,
      passiveText: 'Fin de tour : soigne 1 PV à tes unités Flots.',
      activeText: 'Invoque un Marqueur 1/1 avec Provocation.',
      activeCost: 1,
      icon: Icons.water,
      deck: [
        'guerriere_flots', 'guerriere_flots', 'guerriere_flots',
        'vague_deferlante', 'vague_deferlante',
        'sanctuaire_aquatique', 'recrue_braise',
        'druide_verdant', 'eclaireur_orage',
        'abyssal_corrompu', 'paladin_lumineux',
        'boule_de_feu', 'eclair_chaine',
        'bastion_lumineux', 'tour_de_garde', 'coeur_tonnerre',
      ],
    ),
    CbHero(
      id: 'lysara',
      name: 'Lysara',
      faction: 'Ordre Verdant',
      element: CbElement.verdant,
      passiveText: 'Tes sorts Verdant coûtent (1) de moins.',
      activeText: 'Rend 4 PV à ton héros. Pioche 1 carte.',
      activeCost: 2,
      icon: Icons.forest,
      deck: [
        'druide_verdant', 'druide_verdant', 'druide_verdant',
        'racines_etouffantes', 'racines_etouffantes',
        'guerriere_flots', 'recrue_braise',
        'eclaireur_orage', 'abyssal_corrompu',
        'paladin_lumineux', 'sanctuaire_aquatique',
        'eclair_chaine', 'boule_de_feu',
        'bastion_lumineux', 'tour_de_garde', 'amulette_braise',
      ],
    ),
    CbHero(
      id: 'zayden',
      name: 'Zayden',
      faction: 'Clan des Orages',
      element: CbElement.orage,
      passiveText: 'Tes unités avec Ruée gagnent +1 ATQ.',
      activeText: 'Donne Ruée à une unité. Elle inflige 2 dégâts.',
      activeCost: 2,
      icon: Icons.thunderstorm,
      deck: [
        'eclaireur_orage', 'eclaireur_orage', 'eclaireur_orage',
        'eclair_chaine', 'eclair_chaine',
        'coeur_tonnerre', 'pylone_orageux',
        'recrue_braise', 'guerriere_flots',
        'abyssal_corrompu', 'paladin_lumineux',
        'boule_de_feu', 'druide_verdant',
        'bastion_lumineux', 'amulette_braise', 'tour_de_garde',
      ],
    ),
    CbHero(
      id: 'morvan',
      name: 'Morvan',
      faction: "L'Empreinte du Vide",
      element: CbElement.vide,
      passiveText: 'Une unité alliée meurt → pioche 1 carte.',
      activeText: 'Détruit une unité ennemie à 3 PV ou moins.',
      activeCost: 3,
      icon: Icons.blur_on,
      deck: [
        'abyssal_corrompu', 'abyssal_corrompu', 'abyssal_corrompu',
        'boule_de_feu', 'boule_de_feu',
        'recrue_braise', 'guerriere_flots',
        'druide_verdant', 'eclaireur_orage',
        'paladin_lumineux', 'pylone_orageux',
        'eclair_chaine', 'vague_deferlante',
        'bastion_lumineux', 'tour_de_garde', 'amulette_braise',
      ],
    ),
    CbHero(
      id: 'orion',
      name: 'Orion',
      faction: 'Sanctuaire Lumière',
      element: CbElement.lumiere,
      passiveText: 'Début de ton tour : +1 Bouclier au héros.',
      activeText: 'Confère Bouclier (4) à une unité alliée.',
      activeCost: 2,
      icon: Icons.wb_sunny,
      deck: [
        'paladin_lumineux', 'paladin_lumineux',
        'bastion_lumineux', 'bastion_lumineux', 'bastion_lumineux',
        'recrue_braise', 'guerriere_flots',
        'druide_verdant', 'eclaireur_orage',
        'abyssal_corrompu', 'tour_de_garde',
        'boule_de_feu', 'eclair_chaine',
        'sanctuaire_aquatique', 'amulette_braise', 'coeur_tonnerre',
      ],
    ),
  ];
}
